In [1]:
from load_ud_dataset import load_ud_dataset, UD_GERMAN_SPLITS

In [2]:
UD_GERMAN_GSD_SPLITS = {
    'train': 'de_gsd-ud-train.conllu',
    'dev': 'de_gsd-ud-dev.conllu',
    'test': 'de_gsd-ud-test.conllu',
}
ud_path = "../data/UD_German-GSD"

In [3]:
ud = load_ud_dataset(ud_path, splits_filemap=UD_GERMAN_SPLITS[0])

/opt/anaconda3/envs/morph/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loaded train: 13813 sentences
Loaded dev: 799 sentences
Loaded test: 977 sentences

In [4]:
ud

DatasetDict({
    train: Dataset({
        features: ['tokens', 'sent_id', 'text'],
        num_rows: 13813
    })
    dev: Dataset({
        features: ['tokens', 'sent_id', 'text'],
        num_rows: 799
    })
    test: Dataset({
        features: ['tokens', 'sent_id', 'text'],
        num_rows: 977
    })
})

In [9]:
lookup_dict = pd.read_csv("german_ud_lookup_dictionary.csv")
lookup_dict.head()

/var/folders/cp/gk01f5vx6hsdhrv8bptt9l440000gn/T/ipykernel_46997/3561946569.py:1: DtypeWarning: Columns (4,6) have mixed types. Specify dtype option on import or set low_memory=False.
  lookup_dict = pd.read_csv("german_ud_lookup_dictionary.csv")

  Lemma Case Number Gender Degree   Upos Inflection Forms
0     A  Dat   Sing   Neut    NaN  PROPN        NaN     A
1     A  Dat   Sing    Fem    NaN  PROPN        NaN     A
2     A  Dat   Sing    Fem    NaN   NOUN        NaN     A
3     A  Acc   Sing    NaN    NaN  PROPN        NaN     A
4     A  Dat   Sing   Masc    NaN  PROPN        NaN     A

In [10]:
set(lookup_dict.Upos)

{'ADJ', 'ADP', 'ADV', 'DET', 'NOUN', 'NUM', 'PRON', 'PROPN', 'X'}

In [11]:
# how many rows has no Gender?
lookup_dict[lookup_dict.Gender.isna()]

         Lemma Case Number Gender Degree   Upos Inflection     Forms
3            A  Acc   Sing    NaN    NaN  PROPN        NaN         A
8       A.V.G.  Dat   Sing    NaN    NaN  PROPN        NaN    A.V.G.
14         A36  Acc   Sing    NaN    NaN  PROPN        NaN       A36
20         ABB  Dat   Sing    NaN    NaN  PROPN        NaN       ABB
23         ABC  Dat   Sing    NaN    NaN  PROPN        NaN       ABC
...        ...  ...    ...    ...    ...    ...        ...       ...
121720  üblich  Dat   Plur    NaN    Pos    ADJ        NaN  üblichen
121730  üblich  Acc   Plur    NaN    Pos    ADJ     Strong   übliche
121734   übrig  Dat   Plur    NaN    Pos    ADJ       Weak   übrigen
121742   übrig  Dat   Sing    NaN    Pos    ADJ     Strong   übrigen
121744   übrig  Dat    NaN    NaN    NaN    ADJ     Strong   übrigen

[7085 rows x 8 columns]

In [12]:
# how many rows has no Number?
lookup_dict[lookup_dict.Number.isna()]

,Lemma,Case,Number,Gender,Degree,Upos,Inflection,Forms
47,ACT,Acc,NaN,NaN,NaN,PROPN,NaN,ACT
59,ADSL,Acc,NaN,NaN,NaN,NOUN,NaN,ADSL
110,AFR,Dat,NaN,NaN,NaN,NOUN,NaN,AFR
117,AGBs,Dat,NaN,NaN,NaN,NOUN,NaN,AGBs
154,AIDS,Dat,NaN,NaN,NaN,NOUN,NaN,AIDS
...,...,...,...,...,...,...,...,...
121425,über,Dat,NaN,NaN,NaN,ADP,NaN,über
121610,überschreiben,Dat,NaN,NaN,Pos,ADJ,Weak,überschrieben
121676,überwiegend,Dat,NaN,NaN,Pos,ADJ,NaN,überwiegend
121711,üblich,Dat,NaN,NaN,Pos,ADJ,Weak,üblich
121744,übrig,Dat,NaN,NaN,NaN,ADJ,Strong,übrigen

In [13]:
import csv
import pandas as pd

In [14]:
dative_spans = pd.read_csv("dative_spans/german_datives_all.csv")
set(dative_spans.preposition)

{'an',
 'auf',
 'aus',
 'bei',
 'hinter',
 'in',
 'mit',
 'nach',
 nan,
 'neben',
 'seit',
 'unter',
 'von',
 'vor',
 'zu',
 'zwischen',
 'über'}

In [15]:
# find the row with the preposition "nordwestlich"
dative_spans[dative_spans.preposition == "nordwestlich"]

Empty DataFrame
Columns: [sent_id, sentence, span, head_form, head_lemma, head_upos, case_marker, preposition, dative_type, relation, governor, governor_upos, split]
Index: []